version: '2'

networks:
  prodnetwork:
    driver: bridge

services:
 nexus:
  build: ./nexus
  ports:
    - "8081:8081"
  volumes:
    - C:\apps\nexus\nexus-data:/nexus-data
 arquillian:
   build: ./wildfly
   ports:
     - "10080:10080"
     - "11990:11990"
   volumes:
     - C:\apps\arquillian\wildfly\wildfly-10.1.0.Final:/opt/jboss/wildfly
   networks:
    - prodnetwork
 jenkins:
  build: ./jenkins
  ports:
    - "8000:8080"
  networks:
    - prodnetwork
  volumes:
    - C:\apps\jenkins-docker:/var/jenkins_home
    - C:\apps\nexus\repository:/nexus/repository
  depends_on:
    - arquillian
    - sonar
    - nexus
  environment:
    - NEXUS_PORT=8081
    - SONAR_PORT=9000
    - SONAR_DB_PORT=5432
    - LANG=en_US.UTF-8
 sonar:
  build: ./sonar
  ports:
   - "9000:9000"
   - "15432:5432"
  networks:
    - prodnetwork
  depends_on:
    - sonardb
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
   - SONARQUBE_JDBC_USERNAME=sonar
   - SONARQUBE_JDBC_PASSWORD=sonar
   
 sonardb:
  networks:
    - prodnetwork
  image: postgres
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar

