version: '3'

networks:
  devnetwork:
    driver: bridge  

services:
 nexus:
  image: sonatype/nexus3 
  ports:
    - "8081:8081"
  volumes:
    - C:\apps\nexus\nexus-data:/nexus-data
  networks:
    - devnetwork
  hostname: "nexus"

 arquillian:
   build: ./wildfly
   ports:
     - "10080:10080"
     - "11990:11990"
   volumes:
     - C:\etc\opt:/etc/opt
   networks:
    - devnetwork
   hostname: "arquillian"

 jenkins:
  build: ./jenkins
  ports:
    - "8000:8080"
  networks:
    - devnetwork
  volumes:
    - C:\etc\opt\text-analysis-project:/etc/opt/text-analysis-project
    - C:\apps\jenkins-docker:/var/jenkins_home
    - C:\apps\nexus\repository:/nexus/repository
  depends_on:
    - arquillian
    - sonarqube
    - nexus
  environment:
    - NEXUS_PORT=8081
    - SONAR_PORT=9000
    - SONAR_DB_PORT=5432
    - LANG=en_US.UTF-8
  hostname: "jenkins"
    
 sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - devnetwork
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
    volumes:
      - C:\apps\sonarqube\conf:/opt/sonarqube/conf
      - C:\apps\sonarqube\data:/opt/sonarqube/data
      - C:\apps\sonarqube\extensions:/opt/sonarqube/extensions
      - C:\apps\sonarqube\lib\bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    depends_on:
      - sonardb
    hostname: "sonarqube"
   
 sonardb:
  ports:
    - "5432:5432"
  networks:
    - devnetwork
  image: postgres
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar
   
 jaeger:
  image: jaegertracing/all-in-one:1.8
  environment:
    - COLLECTOR_ZIPKIN_HTTP_PORT=9411
  ports: 
    - "5775:5775/udp"
    - "6831:6831/udp"
    - "6832:6832/udp"
    - "5778:5778"
    - "16686:16686"
    - "14268:14268"
    - "9411:9411"
  networks: 
    - devnetwork
  hostname: "jaeger"

